name: Friendly AI reply to comments (MCP always on)

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write
  models: read

jobs:
  reply:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest

    steps:
      - name: Prepare ultra-lean prompt files (truncate input)
        run: |
          mkdir -p .github/prompts
          # Minimal system prompt
          cat > .github/prompts/system.txt <<'SYS'
          Reply in ≤40 words. Output ONLY the reply text.
          SYS
                    # Keep the comment tiny to leave headroom under the 8k cap
                    printf "%s" "${{ github.event.comment.body }}" | head -c 1200 > .github/prompts/comment.txt
                    # Minimal structured prompt (forces non-legacy format)
                    cat > .github/prompts/reply.prompt.yml <<'PR'
          messages:
            - role: system
              content: "{{system}}"
            - role: user
              content: |
                Comment by @{{author}} on "{{title}}":
                ---
                {{comment}}
                ---
                Repo: {{repo}}
          model: openai/gpt-4o-mini
          PR

      - name: Draft reply (MCP enabled)
        id: ai
        uses: actions/ai-inference@v2
        env:
          # Ask the hosted MCP server to advertise only these toolsets (may be partially honored)
          GITHUB_TOOLSETS: repos,gists
          GITHUB_DYNAMIC_TOOLSETS: 1
        with:
          enable-github-mcp: true
          # Inference token (can be GITHUB_TOKEN); MCP requires a PAT
          token: ${{ secrets.GITHUB_TOKEN }}
          github-mcp-token: ${{ secrets.GH_MCP_PAT }}
          # Keep completion short to save room
          max-tokens: 80
          system-prompt-file: .github/prompts/system.txt
          prompt-file: .github/prompts/reply.prompt.yml
          input: |
            author: ${{ github.event.comment.user.login }}
            title: ${{ github.event.issue.title }}
            repo: ${{ github.repository }}
            system: ./.github/prompts/system.txt
          file_input: |
            comment: .github/prompts/comment.txt

      - name: Post reply
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            const reply = ${{ toJSON(steps.ai.outputs.response) }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: reply
            });
