name: Friendly AI reply to comments

on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write          # needed to post a comment on Issues
  pull-requests: write   # needed to post a comment on PRs
  models: read           # required by actions/ai-inference

jobs:
  reply:
    if: ${{ github.actor != 'github-actions[bot]' }} # avoid loops
    runs-on: ubuntu-latest
    steps:
      - name: Draft a natural reply with GitHub Models
        id: ai
        uses: actions/ai-inference@v2
        with:
          # Optional: choose a smaller model for speed/cost
          # model: openai/gpt-4o-mini
          system-prompt: >
            You are a helpful, concise maintainer assistant.
            Read the user's comment and write a friendly reply
            that matches their tone and moves the conversation forward.
            Do not include any preamble or labels—output ONLY the reply text.
          prompt: |
            Comment by @${{ github.event.comment.user.login }} on "${{ github.event.issue.title }}":
            ---
            ${{ github.event.comment.body }}
            ---
            Repo: ${{ github.repository }}

      - name: Post reply
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.issue.number;
            // Use toJSON to safely pass multiline/model text
            const reply = ${{ toJSON(steps.ai.outputs.response) }};
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number,
              body: reply
            });
